name: build

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      # - master
      - rearch
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

env:
  # Keep for Dart SDK reporting
  PUB_ENVIRONMENT: bot.github
  # LTS
  NODE_VERSION: 16
  # Script location
  BASE_DIR: ${{ github.workspace }}
  TOOL_DIR: ${{ github.workspace }}/tool

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: tool/test.sh
        continue-on-error: true
        env:
          DART_CHANNEL: ${{ matrix.sdk }}

  deploy:
    if: ${{ github.event_name == 'push' && 
            github.ref == 'refs/heads/master' && 
            github.repository == 'dart-lang/site-www' }}
    needs:
      - test
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: default
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make build
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g firebase-tools
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: tool/check-links.sh
      - run: make deploy-ci

  stage:
    if: ${{ github.event_name == 'push' &&  github.ref == 'refs/heads/rearch' }}
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: dash-site-dev
      FIREBASE_CHANNEL: dart
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: dpkg --print-architecture
      - run: tool/fetch-dart-sdk-sums.sh
      - run: tool/fetch-node-ppa-sum.sh
      - run: make build
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g firebase-tools
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: tool/check-links.sh
      - run: make stage
