name: build

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      # - master
      - rearch
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

env:
  # Keep for Dart SDK reporting
  PUB_ENVIRONMENT: bot.github

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: tool/test.sh
        env:
          BASE_DIR: ${{ github.workspace }}
          TOOL_DIR: ${{ github.workspace }}/tool"

  deploy:
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/master' && 
      github.repository == 'dart-lang/site-www'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make build
      - run: make deploy-ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  stage:
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/rearch' && 
      github.repository == 'VGVentures/dart-site-www'
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: dash-site-dev
      FIREBASE_CHANNEL: dart
      NODE_VERSION: 16
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: dpkg --print-architecture
      - run: tool/fetch-dart-sdk-sums.sh
      - run: tool/fetch-node-ppa-sum.sh
      - run: make build
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g firebase-tools linkinator
      - run: tool/check-links.sh
      - run: make stage
